version: '3.8'

services:
  wordpress_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bedrock_php
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    container_name: bedrock_nginx
    depends_on:
      - wordpress_php
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8083:80"

  database:
    image: mysql:8.0
    container_name: wordpress_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bedrock
      MYSQL_USER: bedrock_user
      MYSQL_PASSWORD: bedrock_password

volumes:
  db_data:
