apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock
  namespace: bedrock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bedrock
  template:
    metadata:
      labels:
        app: bedrock
    spec:
      containers:
      - name: bedrock
        image: meu-registry/bedrock:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: bedrock-config
        - secretRef:
            name: bedrock-secrets
